imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@OperatorBundle/Resources/config/services.yml" }
    - { resource: "@AnalyzerBundle/Resources/config/services.yml" }
    - { resource: "@SiteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache:  false
    form_themes:
            - LexikFormFilterBundle:Form:form_div_layout.html.twig


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                DATE_FORMAT: AppBundle\DQL\DateFormatFunction
            string_functions:
                TIME_TO_SEC: AppBundle\DQL\TimeToSecFunction
                TIMEDIFF: AppBundle\DQL\TimeDiffFunction
                SPLIT_STRING: AppBundle\DQL\SplitStringFunction
                REPLACE_PIPE: AppBundle\DQL\ReplacePipeFunction
                GREATEST: AppBundle\DQL\GreatestFunction
                LEAST: AppBundle\DQL\LeastFunction
                REPLACE: AppBundle\DQL\ReplaceFunction
                GROUP_CONCAT: AppBundle\DQL\GroupConcatFunction
                IF: AppBundle\DQL\IfFunction
                #REGEXP: AppBundle\DQL\RegexpFunction
                REGEXP: DoctrineExtensions\Query\Mysql\Regexp



# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle,ManagerBundle,AnalyzerBundle,OperatorBundle,SiteBundle,FOSUserBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

sensio_framework_extra:
    request:
        converters: true
        auto_convert: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

lexik_form_filter:
    where_method: ~  # null | and | or
    force_case_insensitivity: false
    listeners:
        doctrine_orm: true
        doctrine_dbal: false
        doctrine_mongodb: false
knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template


fr3d_ldap:
    driver:
        host:                netsrv1.iram.fr
        port:                636    # Optional
#       username:            foo    # Optional
#       password:            bar    # Optional
        bindRequiresDn:      true   # Optional
#       baseDn:              ou=users, dc=host, dc=foo   # Optional
#       accountFilterFormat: (&(uid=%s)) # Optional. sprintf format %s will be the username
#       optReferrals:        false  # Optional
        useSsl:              true   # Enable SSL negotiation. Optional
#       useStartTls:         true   # Enable TLS negotiation. Optional
#       accountCanonicalForm: 3 # ACCTNAME_FORM_BACKSLASH this is only needed if your users have to login with something like HOST\User
#       accountDomainName: HOST
#       accountDomainNameShort: HOST # if you use the Backslash form set both to Hostname than the Username will be converted to HOST\User
    user:
        baseDn: ou=People, dc=iram, dc=fr
        filter: (&(ObjectClass=Person))
#       usernameAttribute: uid # Optional
        attributes:          # Specify ldap attributes mapping [ldap attribute, user object method]
           - { ldap_attr: uidNumber,  user_method: setId }
           - { ldap_attr: uid,  user_method: setUsername }
           - { ldap_attr: cn,   user_method: setName }
           - { ldap_attr: mail,  user_method: setEmail }

#   service:
#       user_hydrator: fr3d_ldap.user_hydrator.default # Overrides default user hydrator
#       ldap_manager: fr3d_ldap.ldap_manager.default   # Overrides default ldap manager
#       ldap_driver: fr3d_ldap.ldap_driver.zend        # Overrides default ldap driver
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
            address: npm@iram.fr
            sender_name: NoemaParetoManager

sonata_seo:
    page:
        title: NPM
        metas:
            name:
                description: Noema Pareto Manager
                keywords: store
cmf_seo:
    title: "%%content_title%% - Symfony"
    description: seo.description
    content_key: test
    original_route_pattern: redirect

#knp_snappy:
#    pdf:
#        enabled:    true
#        #binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64
#        binary:     /usr/local/bin/wkhtmltopdf

