# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    app.form.type.breakdown:
#        class: AppBundle\Form\BreakdownType
#        tags:
#            - { name: form.type }
#        arguments: ['@?doctrine']
    operator.form.type.breakdown:
        class: OperatorBundle\Form\BreakdownType
        tags:
            - { name: form.type }
        arguments: ['@?doctrine']
    app.descriptor.subscriber:
        class: AppBundle\Subscriber\PaginateDescriptorSubscriber
        tags:
            - { name: knp_paginator.subscriber }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    app.simpleLiveEditor:
            class: AppBundle\Service\SimpleLiveEditor
            arguments: ['@service_container','@templating','@doctrine.orm.entity_manager','@request_stack']
