<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Descriptor extends \AppBundle\Entity\Descriptor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'label', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'tag', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'category', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'synonyms', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'breakdowns'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'label', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'tag', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'category', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'synonyms', '' . "\0" . 'AppBundle\\Entity\\Descriptor' . "\0" . 'breakdowns'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Descriptor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function preTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preTag', []);

        return parent::preTag();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\AppBundle\Entity\DescriptorCategory $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addSynonym(\AppBundle\Entity\Synonym $synonym)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSynonym', [$synonym]);

        return parent::addSynonym($synonym);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSynonym(\AppBundle\Entity\Synonym $synonym)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSynonym', [$synonym]);

        return parent::removeSynonym($synonym);
    }

    /**
     * {@inheritDoc}
     */
    public function getSynonyms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSynonyms', []);

        return parent::getSynonyms();
    }

    /**
     * {@inheritDoc}
     */
    public function addBreakdown(\AppBundle\Entity\Breakdown $breakdown)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBreakdown', [$breakdown]);

        return parent::addBreakdown($breakdown);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBreakdown(\AppBundle\Entity\Breakdown $breakdown)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBreakdown', [$breakdown]);

        return parent::removeBreakdown($breakdown);
    }

    /**
     * {@inheritDoc}
     */
    public function getBreakdowns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBreakdowns', []);

        return parent::getBreakdowns();
    }

    /**
     * {@inheritDoc}
     */
    public function setTag($tag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTag', [$tag]);

        return parent::setTag($tag);
    }

    /**
     * {@inheritDoc}
     */
    public function getTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTag', []);

        return parent::getTag();
    }

}
