<?php

namespace AppBundle\Entity;

/**
 * AnalyzeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyzeRepository extends \Doctrine\ORM\EntityRepository
{
}
