<?php

namespace AppBundle\Entity;

/**
 * BoringMachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoringMachineRepository extends \Doctrine\ORM\EntityRepository
{
}
