<?php

namespace AppBundle\Entity;

/**
 * BreakdownsInterferosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BreakdownsInterferosRepository extends \Doctrine\ORM\EntityRepository
{
}
