<?php

namespace AppBundle\Entity;

/**
 * DescriptorCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptorCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
