<?php

namespace AppBundle\Entity;

/**
 * InterferoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterferoRepository extends \Doctrine\ORM\EntityRepository
{
}
