manager_homepage:
    path:     /manager
    defaults: { _controller: ManagerBundle:Default:index }

manager_synonym:
    path:     /manager/synonym
    defaults: { _controller: ManagerBundle:Synonym:index }

manager_synonym_new:
    path:     /manager/synonym/new
    defaults: { _controller: ManagerBundle:Synonym:new }

manager_synonym_show:
    path:     /manager/synonym/{id}/show
    defaults: { _controller: ManagerBundle:Synonym:show }

manager_synonym_show_descriptor:
    path:     /manager/synonym/descriptor/{id}/show
    defaults: { _controller: ManagerBundle:Synonym:descriptor }

manager_synonym_edit:
    path:     /manager/synonym/{id}/edit
    defaults: { _controller: ManagerBundle:Synonym:edit }

manager_synonym_delete:
    path:     /manager/synonym/{id}/delete
    defaults: { _controller: ManagerBundle:Synonym:delete }


manager_descriptor:
    path:     /manager/descriptor
    defaults: { _controller: ManagerBundle:Descriptor:index }

manager_descriptor_new:
    path:     /manager/descriptor/new
    defaults: { _controller: ManagerBundle:Descriptor:new }

manager_descriptor_show:
    path:     /manager/descriptor/{id}/show
    defaults: { _controller: ManagerBundle:Descriptor:show }

manager_descriptor_edit:
    path:     /manager/descriptor/{id}/edit
    defaults: { _controller: ManagerBundle:Descriptor:edit }

manager_descriptor_delete:
    path:     /manager/descriptor/{id}/delete
    defaults: { _controller: ManagerBundle:Descriptor:delete }

manager_interfero:
    path:     /manager/interfero
    defaults: { _controller: ManagerBundle:Interfero:index }

manager_interfero_new:
    path:     /manager/interfero/new
    defaults: { _controller: ManagerBundle:Interfero:new }

manager_interfero_edit:
    path:     /manager/interfero/{id}/edit
    defaults: { _controller: ManagerBundle:Interfero:edit }

manager_interfero_delete:
    path:     /manager/interfero/{id}/delete
    defaults: { _controller: ManagerBundle:Interfero:delete }

ajax_synonym_delete:
    path:     /ajaxSynonymDelete
    defaults: { _controller: ManagerBundle:Ajax:deleteSynonym }
    options:
        expose: true

ajax_descriptor_delete:
    path:     /ajaxDescriptorDelete
    defaults: { _controller: ManagerBundle:Ajax:deleteDescriptor }
    options:
        expose: true

