<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Person extends \AppBundle\Entity\Person implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Person' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Person' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Person' . "\0" . 'groupies', '' . "\0" . 'AppBundle\\Entity\\Person' . "\0" . 'gifts', 'persons_qualities', 'persons_milestones'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Person' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Person' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Person' . "\0" . 'groupies', '' . "\0" . 'AppBundle\\Entity\\Person' . "\0" . 'gifts', 'persons_qualities', 'persons_milestones'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Person $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function addGroupy(\AppBundle\Entity\Groupy $groupy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroupy', [$groupy]);

        return parent::addGroupy($groupy);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroupy(\AppBundle\Entity\Groupy $groupy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroupy', [$groupy]);

        return parent::removeGroupy($groupy);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupies', []);

        return parent::getGroupies();
    }

    /**
     * {@inheritDoc}
     */
    public function addGift(\AppBundle\Entity\Gift $gift)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGift', [$gift]);

        return parent::addGift($gift);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGift(\AppBundle\Entity\Gift $gift)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGift', [$gift]);

        return parent::removeGift($gift);
    }

    /**
     * {@inheritDoc}
     */
    public function getGifts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGifts', []);

        return parent::getGifts();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersonsQuality(\AppBundle\Entity\PersonsQualities $personsQuality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersonsQuality', [$personsQuality]);

        return parent::addPersonsQuality($personsQuality);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersonsQuality(\AppBundle\Entity\PersonsQualities $personsQuality)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersonsQuality', [$personsQuality]);

        return parent::removePersonsQuality($personsQuality);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonsQualities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonsQualities', []);

        return parent::getPersonsQualities();
    }

    /**
     * {@inheritDoc}
     */
    public function addMilestone(\AppBundle\Entity\PersonsMilestones $milestone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMilestone', [$milestone]);

        return parent::addMilestone($milestone);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMilestone(\AppBundle\Entity\PersonsMilestones $milestone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMilestone', [$milestone]);

        return parent::removeMilestone($milestone);
    }

    /**
     * {@inheritDoc}
     */
    public function getMilestones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMilestones', []);

        return parent::getMilestones();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersonsMilestone(\AppBundle\Entity\PersonsMilestones $personsMilestone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersonsMilestone', [$personsMilestone]);

        return parent::addPersonsMilestone($personsMilestone);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersonsMilestone(\AppBundle\Entity\PersonsMilestones $personsMilestone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersonsMilestone', [$personsMilestone]);

        return parent::removePersonsMilestone($personsMilestone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonsMilestones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonsMilestones', []);

        return parent::getPersonsMilestones();
    }

}
